-- MySQL Script generated by MySQL Workbench
-- Wed Oct 17 15:19:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`leerling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leerling` (
  `leerling_id` SMALLINT(10) NOT NULL,
  `birth_date` DATE NOT NULL,
  `leerling_naam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`leerling_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leraren`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leraren` (
  `leraren_id` INT NOT NULL,
  `leraar_naam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`leraren_id`),
  UNIQUE INDEX `idLeeraren_UNIQUE` (`leraren_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vakken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vakken` (
  `vakken_id` INT NOT NULL,
  `vak_naam` VARCHAR(45) NOT NULL,
  `vak_onderwerp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`vakken_id`),
  UNIQUE INDEX `idVakken_UNIQUE` (`vakken_id` ASC) VISIBLE,
  UNIQUE INDEX `vak_naam_UNIQUE` (`vak_naam` ASC) VISIBLE,
  UNIQUE INDEX `vak_onderwerp_UNIQUE` (`vak_onderwerp` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leerling_vakken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leerling_vakken` (
  `leerling_id` INT NOT NULL,
  `vak_id` INT NOT NULL,
  CONSTRAINT `leerling_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`leerling` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vak_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`vakken` ()
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leraar_vak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leraar_vak` (
  `leraar_id` INT NOT NULL,
  `vak_id` INT NOT NULL,
  CONSTRAINT `lidLeeraren`
    FOREIGN KEY ()
    REFERENCES `mydb`.`leraren` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idVakken`
    FOREIGN KEY ()
    REFERENCES `mydb`.`vakken` ()
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`klassen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`klassen` (
  `klassen_id` INT NOT NULL,
  `klassen_naam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`klassen_id`),
  UNIQUE INDEX `klassen_id_UNIQUE` (`klassen_id` ASC) VISIBLE,
  UNIQUE INDEX `klassen_naam_UNIQUE` (`klassen_naam` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leerling_klas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leerling_klas` (
  `leerling_id` INT NOT NULL,
  `klassen_id` INT NOT NULL,
  CONSTRAINT `klassen_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`klassen` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `leerling_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`leerling` ()
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
